#!/usr/bin/env ruby
#
# This script connects to IB API, subscribes to account info and prints out
# messages received from IB (update every 3 minute or so)
# and prints a summay every 60 seconds

require 'rubygems'
require 'bundler/setup'
$LOAD_PATH.unshift File.expand_path(File.dirname(__FILE__) + '/../lib')
require 'ib-ruby'

# Start the Gateway and initialize the active-accounts
#gw = IB::Gateway.new subscribe_account_infos: false,  host:  'localhost'
gw = IB::Gateway.new subscribe_account_infos: true,  host:  'localhost'
#   continous fetching of Account- and Portfolio-Values only works with one active account
#gw.initialize_account_infos continously:  true
gw.connect

# subscribe to the PortfolioValue-Event and print a message as it appears ( for debugging reasons ) 
# gw.tws.subscribe( :PortfolioValue ) do |msg|
#   puts "PortfolioValueEvent --> #{msg.account_name} "
#   puts msg.to_human
# end
last_update =  Time.now
gw.get_account_data 
## print out the updated values  
## perfom the operation in a thread-safe environment  
## (this is not really nessesary here, because the operations are performed serial )

while 1==1 do
  puts "\n\n--------------- #{Time.now} --------------------------------------"
  # not thread save: gw.active_accounts do | account | 
  gw.for_active_accounts do | account |
    if account.last_update > last_update
      puts "Contracts ------------------> #{account.account } <----------------------"
      puts account.contracts.map( &:to_human ).join( "\n" )
      puts "-----------------"

      puts "Portfolio_values -----------> #{account.account } <----------------------"
      puts account.portfolio_values.map &:to_human
      puts "-----------------"

      puts "Account_values -------------> #{account.account } <----------------------"
      ['PNL', 'OptionValue','FundValue','WarrantValue','OptionValue','MarketValue','TotalCash'].each do | key |
	puts account.simple_account_data_scan(key).map{|y| [y.key,y.value,y.currency].join("\t") unless y.value.to_i.zero? }.compact
      end
      puts "-----------------\n\n"
    else
      puts "last update remained at  #{strftime("%d.%m. %X") }"
    end
  end
  last_update = gw.for_active_accounts{ |account|  account.last_update }.max
  sleep  60
  gw.get_account_data 
end

__END__
Expected output

DU167348 :: Requesting AccountData DU167348 => Count of AccountValues: 196 DU167349 :: Requesting AccountData DU167349 => Count of AccountValues: 196 

--------------- 2015-10-14 07:14:15 +0200 --------------------------------------
  Contracts ------------------> DU167348 <----------------------
  <Stock: BLUE EUR>
<Stock: CBA AUD>
<Stock: CIEN USD>
<Stock: CSCO USD>
<Stock: DBA USD>
<Future: ESTX50 20151218 EUR>
<Stock: GE USD>
<Stock: LHA EUR>
<Stock: NEU USD>
-----------------
  Portfolio_values -----------> DU167348 <----------------------
  BLUE (720): Market 23.6800003 price 17049.6 value; PnL: 746.31 unrealized, 0.0 realized;>
CBA (1004): Market 74.55999755 price 74858.24 value; PnL: -4822.66 unrealized, 0.0 realized;>
CIEN (812): Market 21.8299999 price 17725.96 value; PnL: -1498.14 unrealized, 0.0 realized;>
CSCO (44): Market 27.8500004 price 1225.4 value; PnL: 281.6 unrealized, 0.0 realized;>
DBA (1365): Market 21.51000025 price 29361.15 value; PnL: -5202.01 unrealized, 0.0 realized;>
FESX DEC 15 (2): Market 3211.0 price 64220.0 value; PnL: -644.0 unrealized, 0.0 realized;>
GE (-500): Market 27.87000085 price -13935.0 value; PnL: -1454.65 unrealized, 0.0 realized;>
LHA (10124): Market 13.5550003 price 137230.82 value; PnL: -18615.31 unrealized, 0.0 realized;>
NEU (1): Market 385.23999025 price 385.24 value; PnL: 108.25 unrealized, 0.0 realized;>
-----------------
  Account_values -------------> DU167348 <----------------------
  StockMarketValue  74858 AUD
StockMarketValue  232236  BASE
StockMarketValue  154280  EUR
StockMarketValue  34763	USD
TotalCashBalance  -77095  AUD
TotalCashBalance  605565  BASE
TotalCashBalance  4334	EUR
TotalCashBalance  -740732 JPY
TotalCashBalance  746772  USD
TotalCashValue	605564.90 EUR
TotalCashValue-C  29681.72  EUR
TotalCashValue-S  575883.18 EUR
-----------------

  Contracts ------------------> DU167349 <----------------------
  <Stock: AGU USD>
<Stock: ALB USD>
<Stock: BLUE EUR>
<Stock: CBA AUD>
<Stock: CIEN USD>
<Stock: CSCO USD>
<Stock: D USD>
<Stock: DBA USD>
<Stock: GE USD>
<Stock: LHA EUR>
<Option: LHA 20151218 call 15.0  EUR>
<Stock: T USD>
-----------------
  Portfolio_values -----------> DU167349 <----------------------
  AGU (100): Market 95.05999755 price 9506.0 value; PnL: 226.0 unrealized, 0.0 realized;>
ALB (48): Market 50.2599983 price 2412.48 value; PnL: -515.04 unrealized, 0.0 realized;>
BLUE (740): Market 23.6800003 price 17523.2 value; PnL: 775.07 unrealized, 0.0 realized;>
CBA (1032): Market 74.55999755 price 76945.92 value; PnL: -4957.15 unrealized, 0.0 realized;>
CIEN (28): Market 21.8299999 price 611.24 value; PnL: -52.52 unrealized, 0.0 realized;>
CSCO (51): Market 27.8500004 price 1420.35 value; PnL: 326.4 unrealized, 0.0 realized;>
D (1264): Market 71.90000155 price 90881.6 value; PnL: 8571.62 unrealized, 0.0 realized;>
DBA (273): Market 21.51000025 price 5872.23 value; PnL: -421.78 unrealized, 0.0 realized;>
GE (-240): Market 27.87000085 price -6688.8 value; PnL: -681.31 unrealized, 0.0 realized;>
LHA (5146): Market 13.5550003 price 69754.03 value; PnL: -9399.84 unrealized, 0.0 realized;>
C LHA  DEC 15  1500 (-10): Market 0.43377265 price -433.77 value; PnL: 675.23 unrealized, 0.0 realized;>
T (-700): Market 33.2200012 price -23254.0 value; PnL: 649.56 unrealized, 0.0 realized;>
-----------------
  Account_values -------------> DU167349 <----------------------
  StockMarketValue 76946 AUD
StockMarketValue 206934  BASE
OptionMarketValue  -434  BASE
StockMarketValue 87277 EUR
OptionMarketValue  -434  EUR
StockMarketValue 80761 USD
TotalCashValue 715220.32 EUR
TotalCashValue-C 82278.11  EUR
TotalCashValue-S 632942.21 EUR
TotalCashBalance 4217  AUD
TotalCashBalance 715220  BASE
TotalCashBalance 629503  EUR
TotalCashBalance -23264  JPY
TotalCashBalance 94798 USD
-----------------


